internal/assertions/assertions.go, must/must_test.go, test_test.go
nil in Go is more complex than it seems; for some types we need to
use reflection to detect whether they are "really" nil, or if they
are typed nil - which as far as assertions go, would be treated as
nil
=> nobug: fix a bug where nil assertions did not work on some types

internal/assertions/assertions.go, must/must_test.go, test_test.go
EqError and ErrorIs will panic if the errors passed in
are actually nil. They should correctly handle the nil
error case.
Fixes #11
=> gh-11: correctly handle nil errors

README.md, interface.go, interface_test.go, internal/assertions/assertions.go, must/interface.go, must/interface_test.go, must/must.go, must/must_test.go, must/scripts.go, must/scripts_test.go, scripts.go, scripts/generate.sh, scripts_test.go, test.go, test_test.go
This PR adds `PostScript` variadic arguments to each assertion function,
enabling adding more context to test failures.
Examples
```golang
// Add a single Sprintf-string to the output of a failed test assertion.
must.Eq(t, exp, result, must.Note("some more context: %v", value))
```
```
keys_test.go:87: expected equality via cmp.Equal function
↪ Assertion | differential ↷
int(
- 	1,
+ 	2,
)
↪ PostScript | annotation ↷
more context: hello
```
```golang
// Add a formatted key-value map to the output of a failed test assertion.
must.Eq(t, exp, result, must.Map(
"one", 1,
"two", 2,
"fruit", "banana",
))
```
```
↪ Assertion | differential ↷
int(
- 	1,
+ 	2,
)
↪ PostScript | mapping ↷
"one" => 1
"two" => 2
"fruit" => "banana"
```
```golang
// Add the output from a closure to the output of a …
```
=> gh-22: provide a way to add more context on test failures

internal/assertions/assertions.go, must/must.go, must/must_test.go, test.go, test_test.go
Add a `.One` helper
closes #29
=> gh-29: helper method to check value is 1

README.md, internal/assertions/assertions.go, must/must.go, must/must_test.go, must/scripts.go, scripts.go, test.go, test_test.go
This PR introduces breaking changes, where less/greater helpers now
have the expectation come first. This is to be more consistent with
other functions.
Closes https://github.com/shoenig/test/issues/33
=> refactor: expectation always comes first

internal/assertions/assertions.go
=> numbers: use value instead of n in labeling

README.md
The new cmp.Option option can also be used with protocmp, which is essential when using protobuf types.
=> readme: add note about protocmp

internal/assertions/assertions.go, must/must.go, must/must_test.go, test.go, test_test.go
This PR enables `SliceContainsFunc` to accept a different type as the
target from the slice elements type. For example if we have a slice
of Person objects but want to detect if the slice contains a person
with a particular name (string), we can now use a comparator of
signature `func(Person, string) bool` - rather than needing a whole
Person struct for the target.
Closes #88 
Worth noting that technically just the predicate function is sufficient, as is done in the `slices` package https://pkg.go.dev/golang.org/x/exp/slices#ContainsFunc - however in the context of test case assertions I think it's more valuable to have the target value explicitly part of the assertion signature.
=> slices: make slice equality comparator flexible on target type

internal/assertions/assertions.go, must/must.go, must/must_test.go, test.go, test_test.go
This PR adds a ContainsSubset assertion for asserting a Container
contains each element in a slice of elements.
Closes #97 
Note that `ContainsAll` is not technically possible for the `Container` interface which only mandates a `Contains` method - no way to know if it contains _additional_ elements.
=> contains: add ContainsSubset assertion

internal/assertions/assertions.go, must/must.go, must/must_test.go, test.go, test_test.go
Add heper methods that defer to Go json.Valid function for checking
a string or byte slice is valid json.
Closes #103
=> test: add ValidJSON and ValidJSONBytes assertions

interfaces/interfaces.go, internal/assertions/assertions.go, internal/util/slices.go, internal/util/slices_test.go, must/must.go, must/must_test.go, test.go, test_test.go
This PR adds StructEqual which is helpful for verifying that modifying
the fields of a struct will cause the Equal method of the struct to
no longer return true.
e.g. usage
```go
func TestAffinity_Equal(t *testing.T) {
must.Equal[*Affinity](t, nil, nil)
must.NotEqual[*Affinity](t, nil, new(Affinity))
must.StructEqual(t, &Affinity{
LTarget: "left",
RTarget: "right",
Operand: "op",
Weight:  100,
}, []must.Tweak[*Affinity]{{
Field: "LTarget",
Apply: func(a *Affinity) { a.LTarget = "left2" },
}, {
Field: "RTarget",
Apply: func(a *Affinity) { a.RTarget = "right2" },
}, {
Field: "Operand",
Apply: func(a *Affinity) { a.Operand = "op2" },
}, {
Field: "Weight",
Apply: func(a *Affinity) { a.Weight = 50 },
}})
}
```
=> tests: add StructEqual() for verifying Equal method of structs

internal/assertions/assertions.go, must/must.go, must/must_test.go, test.go, test_test.go
This PR makes `EqSliceFunc` accept slices of two different types that
are then compared by the supplied comparator - which accepts one of
each type.
Fixes https://github.com/shoenig/test/issues/107
motivating example use
```go
must.SliceEqFunc(t, []string{
"add",    // PreRun
"update", // Update
"remove", // PostRun
"add",    // PreRun (replacement)
}, ops, func(val regMock.Operation, exp string) bool {
return val.Op == exp
})
```
=> slices: make EqSliceFunc more flexible on types

examples_test.go, must/examples_test.go
=> docs: finish up examples

internal/assertions/assertions.go, must/must.go, must/must_test.go, test.go, test_test.go
=> test: single value variants of MapContainsValue(s) helpers

internal/assertions/assertions.go, must/must.go, must/must_test.go, test.go, test_test.go
#152 
Before `DirMode` func, users had to specify the dir bit using:
```go
FileMode(tc, "/bin", os.ModeDir | 0655)
```
With `DirMode` func, users can omit the `os.ModeDir`
```go
DirMode(tc, "/bin", os.FileMode(0755))
```
Happy easter :smile: :rabbit:
=> test: add `DirMode`, and `DireModeFS`

README.md, must/must.go, test.go
Hi @shoenig, thank you for creating this formidable assertion lib! :)
The type I added is analog to `testify`'s `ErrorAssertionFunc` type that makes it convenient to pass `Error` or `NoError` assertion functions in table driven tests.
Do you like the idea of adding this type?
I wasn't sure what the best placement of the type in the source file would be, so please let me know if you wanna move it somewhere else.
Best,
Cornelius
=> Adding ErrorAssertionFunc function type

.gitignore, scripts/generate.sh
Use the .bak trick suggested in https://stackoverflow.com/a/22084103
Also cleanup the script by applying a function to each file to be generated rather than doing each operation individually for each file.
Fixes #156
=> make: rewrite generate.sh so it works on BSD machines

assert.go, invocations.go, must/assert.go, must/invocations.go
hi!
given this `test_test.go`:
```go
1 package main
2
3 import (
4     "testing"
5
6     "github.com/shoenig/test"
7     "github.com/shoenig/test/must"
8 )
9
10 func TestHelperStack(t *testing.T) {
11     failSadly(t)
12 }
13
14 func failSadly(t *testing.T) {
15     t.Helper()
16     test.NotNil(t, nil)
17     must.NotNil(t, nil)
18 }
```
before this change, error stack shows `assert.go` from this lib:
```
$ go test .
--- FAIL: TestHelperStack (0.00s)
assert.go:14:
test_test.go:16: expected to not be nil; is nil
assert.go:14:
test_test.go:17: expected to not be nil; is nil
```
after, shows my test file(s) with the context relevant to me and my terrible mistakes:
```
$ go test .
--- FAIL: TestHelperStack (0.00s)
test_test.go:11:
test_test.go:16: expected to not be nil; is nil …
```
=> mark more internal funcs as helpers

internal/assertions/assertions.go, invocations_test.go, must/invocations_test.go, must/must.go, must/must_test.go, must/testdata/dir1/file1, scripts/generate.sh, test.go, test_test.go, testdata/dir1/file1
File and directory helpers don't work properly on Windows, and a couple of them even panic. This PR fixes a few underlying problems:
1. `os.DirFS` does not handle Windows paths properly, and `brokenfs` isn't doing the trick to fix it. When those functions validate names, they choke on the colon after the drive letter and return `fs.ErrInvalid`. Perhaps this can be avoided by not providing a drive letter (that seems to be a solution given in https://github.com/golang/go/issues/44279) but that's inconvenient and would probably only work if the file/directory is on the same drive as the working directory. I fixed this by adding having the non-FS helpers use new assertions that call `os` functions instead of `fs` ones.
2. Some file and directory assertions only check for `ErrNotExist` and …
=> Fix broken file and dir helpers on Windows

README.md, must/must_test.go, test_test.go, util/tempfile.go, util/tempfile_test.go
- Adds `TempFile` and related functional settings is in a new `util` package
- Replaces _ad hoc_ temp file helpers in file/dir helper tests
- Bumps version to 1.10.0
fixes #35
=> util: add TempFile helper

util/tempfile.go, util/tempfile_test.go
This implements more of @ccoVeille's suggestions on #168:
- `Path` is now `Dir` and is better documented.
- The tests try multiple options at once.
- There is a new test to ensure `TempFile` fails if dir does not exist. I reorganized `TempFile` to make it easier to test failures.
- The 'Dir' tests now ensure that existing files don't get deleted.
=> util: TempFile improvements

must/must_test.go, test_test.go, util/examples_test.go, util/tempfile.go, util/tempfile_test.go
CC @brandondyck @ccoVeille 
Just shortens `StringData(data)` to `String(data)` and same for `Bytes`. Also adds an [testable example](https://go.dev/blog/examples) for using `util.TempFile`
=> util: shorten data type names and add doc example

skip/skip_test.go
This PR increases the expected minimum cores test core count, because it
fails on this machine I am working on right now with 256 virtual cores.
```
kingpin ~
➜ lscpu | grep On-line
On-line CPU(s) list:                  0-255
```
=> skip: increase test case minimum cores

.gitattributes, examples_test.go, internal/assertions/assertions.go, must/examples_test.go, must/must.go, must/must_test.go, test.go, test_test.go
I also updated .gitattributes to normalize line endings in all text files, because checking out the repo in Windows apparently screwed them up and broke the shell scripts. I think it hadn't bitten me before because I had done my Git operations in WSL.
=> test: Add Equal, Func, and Op variants of SliceContainsSubset and SliceContainsAll
