shoenig/test

internal/assertions/assertions.go, must/must.go, must/must_test.go, test.go, test_test.go
- gh-20: add more helpers around string operations
- gh-20: add regexp compilation assertions
Closes #20
=> gh-20: add more string helper assertions

.github/workflows/ci.yaml, Makefile
- build: use makefile for build operations
- build: bump go and actions version
=> build: use makefile

.github/workflows/ci.yaml, Makefile, must/must_test.go, scripts/changes.sh, test_test.go
- nobug: support macos in tests
- build: run tests also on macos and windows
=> build: also test on macos and windows

internal/assertions/assertions.go, must/must.go, must/must_test.go, test.go, test_test.go
=> slices: assertions for ContainsAll and NotContains

internal/assertions/assertions.go, must/must.go, must/must_test.go, test.go, test_test.go
=> ordered: add Between and BetweenExclusive assertions

internal/assertions/assertions.go, must/must.go, must/must_test.go, test.go, test_test.go
=> tests: assertions for non-positive and non-negative

internal/assertions/assertions.go, must/must.go, must/must_test.go, test.go, test_test.go
=> strings: fix parameter positions (exp, value)

.gitattributes, .github/workflows/ci.yaml, .golangci.yaml, internal/assertions/assertions.go
=> ci: setup golangci-lint action

internal/assertions/assertions.go
=> assertions: fixup missing newlines on outputs

internal/assertions/assertions.go, must/must.go, must/must_test.go, test.go, test_test.go
=> maps: add functions for not contains keys, values

internal/assertions/assertions.go, must/must.go, must/must_test.go, test.go, test_test.go
=> assertions: add an ErrorContains assertion

internal/assertions/assertions.go, must/must.go, test.go, wait/wait.go, wait/wait_test.go
- wait: make timeout and attempts exclusive
- wait: rename to Constraint and add docs
=> wait exclusive

.github/workflows/ci.yaml, .golangci.yaml, must/must_test.go, test_test.go, wait/wait.go, wait/wait_test.go
=> wait: add continual function variant

.github/release.yaml
=> repo: add release.yaml file for automatic changes

internal/assertions/assertions.go, must/must.go, must/must_test.go, test.go, test_test.go
for asserting a slice of elements is increasing or decreasing by using
a comparison function of signature 'func(A, B) int'
=> test: add AscendingCmp and DescendingCmp

internal/assertions/assertions.go, must/must.go, must/must_test.go, test.go, test_test.go
=> test: add SliceNotContainsFunc assertion

examples_test.go
=> examples: add some runnable Go doc examples

examples_test.go, must/examples_test.go, must/must.go, test.go
=> more examples

examples_test.go, must/examples_test.go
#123 .
A couple of examples a day keeps the doctor away! :woman_health_worker:
=> Add more doc examples

examples_test.go, must/examples_test.go
#123 
Yet another day with some more examples :nerd_face: 
Lemme know if the example are clear enough I'm not :100: convinced about `FileContainsFS(t, os.DirFS(os.TempDir()), fName, "bar")` might be less clear than `FileContainsFS(t, "/tmp", "fileName, "bar")` WDYT?
=> docs: add File funcs examples

.github/workflows/ci.yaml
=> ci: run on pull_request
